services:
  mysql:
    image: mysql:8.0
    container_name: mysql_denodo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_mysql
      MYSQL_USER: denodo_user
      MYSQL_PASSWORD: denodo_pwd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres:
    image: postgres:16
    container_name: postgres_denodo
    restart: always
    environment:
      POSTGRES_DB: db_postgres
      POSTGRES_USER: denodo_user
      POSTGRES_PASSWORD: denodo_pwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
  postgres_data: